### ISSUE TITLE
About the dgl and pytorch？

### ISSUE THREAD

**Issue by LayneChai** [YangLiangwei/DGRec#1]
solved

**Comment by Achellesphi** [comment]
Hi, I first ask for the pytorch version and dgl version of DGRec. Because I have a bug while running (dgl._ffi.base.DGLError: Node type name must be specified if there are more than one node types.). I guess it's a version issue. Also, the version I'm using is torch 1.9.0+cu102 and dgl-cu102 0.4.3.post2.
